# Generated by Django 5.1.5 on 2025-01-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecomplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
