# Generated by Django 5.1.5 on 2025-01-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='datecomplete',
        ),
    ]
